db:
  image: postgres
  expose:
    - "5432"
  environment:
    POSTGRES_USER: rails_user
    POSTGRES_PASSWORD: gravn3da
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app # ソースコード変更したらDocker側も即反映されるように
  ports:
    - "3000:3000"
  links:
    - db
  tty: true # for binding.pry
  stdin_open: true # for binding.pry